insert into make (brand, model, capacity) values ('Toyota', 'Prius', 4);
insert into make (brand, model, capacity) values ('Chevrolet', 'Corvette', 6);
insert into make (brand, model, capacity) values ('Jaguar', 'XJ Series', 7);
insert into make (brand, model, capacity) values ('Volvo', 'V50', 6);
insert into make (brand, model, capacity) values ('Subaru', 'SVX', 7);
insert into make (brand, model, capacity) values ('Volkswagen', 'Golf', 2);
insert into make (brand, model, capacity) values ('Mitsubishi', 'Lancer', 3);
insert into make (brand, model, capacity) values ('Toyota', 'TundraMax', 3);
insert into make (brand, model, capacity) values ('Chevrolet', 'G-Series G20', 6);
insert into make (brand, model, capacity) values ('GMC', 'Jimmy', 2);
insert into make (brand, model, capacity) values ('Chrysler', 'PT Cruiser', 7);
insert into make (brand, model, capacity) values ('Ford', 'Thunderbird', 3);
insert into make (brand, model, capacity) values ('Volkswagen', 'Jetta', 3);
insert into make (brand, model, capacity) values ('Ford', 'F250', 7);
insert into make (brand, model, capacity) values ('Chrysler', 'Prowler', 5);
insert into make (brand, model, capacity) values ('Bentley', 'Continental Flying Spur', 7);
insert into make (brand, model, capacity) values ('Ford', 'Aerostar', 7);
insert into make (brand, model, capacity) values ('Toyota', 'Sienna', 5);
insert into make (brand, model, capacity) values ('Pontiac', 'Firebird', 7);
insert into make (brand, model, capacity) values ('Chevrolet', 'S10', 6);
insert into make (brand, model, capacity) values ('Kia', 'Sorento', 7);
insert into make (brand, model, capacity) values ('Mazda', 'Mazda6', 3);
insert into make (brand, model, capacity) values ('Jaguar', 'XK', 2);
insert into make (brand, model, capacity) values ('MINI', 'Clubman', 6);
insert into make (brand, model, capacity) values ('Subaru', 'Legacy', 3);
insert into make (brand, model, capacity) values ('Nissan', 'Armada', 7);
insert into make (brand, model, capacity) values ('Chevrolet', 'Suburban', 3);
insert into make (brand, model, capacity) values ('Porsche', '968', 7);
insert into make (brand, model, capacity) values ('Audi', 'S6', 6);
insert into make (brand, model, capacity) values ('Ferrari', '458 Italia', 7);
